version: '3'

services:
  backuppc:
    container_name: backuppc
    image: backuppc:latest
    restart: always
    ports:
      - "443:8080"
    environment:
      - USE_SSL=true
      - SMTP_MAIL_DOMAIN=mail.example.com
      - SMTP_PORT=587
      - MAIL_FROM=backup@example.com
      - MAIL_AUTH_USER=backup@example.com
      - MAIL_PASSWORD=Password
      - TLS_MODE=on
      - STARTTLS_MODE=on
      - TLS_CERTCHECK=off

    volumes:
      - /local/backuppc/config:/etc/backuppc:rw
      - /local/backuppc/home:/home/backuppc:rw
      #- /local/backuppc/home/.msmtprc:/etc/msmtprc:ro
      - /local/backuppc/data:/data/backuppc:rw
    networks:
            backuppc:
                ipv4_address: 172.20.10.2
networks:
    backuppc:
        ipam:
            driver: default
            config:
                - subnet: 172.20.10.0/24

#volumes:
#  backuppc_etc:
#    external: true
#
#  backuppc_home:
#    external: true
#
#  backuppc_data:
#    external: true
